spring.application.name=fruitgo

spring.datasource.url=jdbc:postgresql://dpg-d8r22l6gvqtc73ee76kg-a:5432/fruitgo
spring.datasource.username=fruitgo_user
spring.datasource.password=t3BaDagsyClA2aFeW8djgcfJxQtoZmR5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080